# Generated by Django 4.1.7 on 2023-05-05 13:14

import calculator.mixins
import calculator.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Original file name')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='File')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Size')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='Meta')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Position Price')),
                ('image', calculator.models.FileField(blank=True, help_text='Image of the position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='calculator.file', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('positions', models.JSONField(null=True)),
                ('total_check', models.IntegerField(null=True, verbose_name='Total Check')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': '-pk',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('image', calculator.models.FileField(blank=True, help_text='Image taken or uploaded', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan', to='calculator.file', verbose_name='Scan')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', related_query_name='scan', to='calculator.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'db_table': 'scan',
            },
            bases=(calculator.mixins.FileUploadToMixin, models.Model),
        ),
    ]
