# Generated by Django 4.1.7 on 2023-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_file_deleted_file_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Original file name'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Size'),
        ),
    ]
