# Generated by Django 4.1.7 on 2023-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_modelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Model name'),
        ),
    ]
