# Generated by Django 4.1.7 on 2023-03-13 16:28

import calculator.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_file_name_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='image',
            field=calculator.models.FileField(blank=True, help_text='Image of the position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='calculator.file', verbose_name='Position'),
        ),
    ]
