# Generated by Django 4.1.7 on 2023-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_transaction_position_transaction_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_check',
            field=models.IntegerField(null=True, verbose_name='Total Check'),
        ),
    ]
