version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 price_calculator.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://gosha:debug@db:5432/calc_db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gosha
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=calc_db

volumes:
  postgres_data:
